(ns clj-standards-boilerplates.iso4217)

(def currencies
  {"ADP" "Andorran Peseta"
   "AED" "UAE Dirham"
   "AFA" "Afghani"
   "ALL" "Lek"
   "AMD" "Armenian Dram"
   "ANG" "Netherlands Antillean Guilder"
   "AON" "New Kwanza"
   "AOR" "Kwanza Reajustado"
   "ARS" "Argentine Peso"
   "ATS" "Shilling"
   "AUD" "Auscurrencyalian Dollar"
   "AWG" "Aruban Guilder"
   "AZM" "Azerbaijanian Manat"
   "BAD" "Dinar"
   "BBD" "Barbados Dollar"
   "BDT" "Taka"
   "BEF" "Belgian Franc"
   "BGL" "Lev"
   "BHD" "Bahraini Dinar"
   "BIF" "Burundi Franc"
   "BMD" "Bermudian Dollar"
   "BND" "Brunei Dollar"
   "BOB" "Boliviano"
   "BOV" "MVDol"
   "BRL" "Brazilian Real"
   "BSD" "Bahamian Dollar"
   "BTN" "Ngulcurrencyum"
   "BWP" "Pula"
   "BYB" "Belarussian Ruble"
   "BZD" "Belize Dollar"
   "CAD" "Candian Dollar"
   "CHF" "Swiss Franc"
   "CLF" "Unidades de Formento"
   "CLP" "Chilean Peso"
   "CNY" "Yuan Renminbi"
   "COP" "Colombian Peso"
   "CRC" "Costa Rican Colon"
   "CUP" "Cuban Peso"
   "CVE" "Cape Verde Escudo"
   "CYP" "Cyprus Pound"
   "CZK" "Czech Koruna"
   "DEM" "Deutsche Mark"
   "DJF" "Djibouti Franc"
   "DKK" "Danish Krone"
   "DOP" "Dominican Peso"
   "DZD" "Algerian Dinar"
   "ECS" "Sucre"
   "ECV" "Unidad de Valor Constante (UVC)"
   "EEK" "Kroon"
   "EGP" "Egyptian Pound"
   "ESP" "Spanish Peseta"
   "ETB" "Ethiopian Birr"
   "FIM" "Markka"
   "FJD" "Fiji Dollar"
   "FKP" "Falkland Islands Pound"
   "FRF" "French Franc"
   "GBP" "Pound Sterling"
   "GEL" "Lari"
   "GHC" "Cedi"
   "GIP" "Gibraltar Pound"
   "GMD" "Dalasi"
   "GNF" "Guinea Franc"
   "GRD" "Drachma"
   "GTQ" "Quetzal"
   "GWP" "Guinea-Bissau Peso"
   "GYD" "Guyana Dollar"
   "HKD" "Hong Kong Dollar"
   "HNL" "Lempira"
   "HRK" "Kuna"
   "HTG" "Gourde"
   "HUF" "Forint"
   "IDR" "Rupiah"
   "IEP" "Irish Pound"
   "ILS" "Shekel"
   "INR" "Indian Rupee"
   "IQD" "Iraqi Dinar"
   "IRR" "Iranian Rial"
   "ISK" "Iceland Krona"
   "ITL" "Italian Lira"
   "JMD" "Jamaican Dollar"
   "JOD" "Jordanian Dinar"
   "JPY" "Yen"
   "KES" "Kenyan Shilling"
   "KGS" "Som"
   "KHR" "Riel"
   "KMF" "Comoro Franc"
   "KPW" "North Korean Won"
   "KRW" "Won"
   "KWD" "Kuwaiti Dinar"
   "KYD" "Cayman Islands Dollar"
   "KZT" "Tenge"
   "LAK" "Kip"
   "LBP" "Lebanese Pound"
   "LKR" "Sri Lanka Rupee"
   "LRD" "Liberian Dollar"
   "LSL" "Loti"
   "LTL" "Lithuanian Litas"
   "LUF" "Luxembourg Franc"
   "LVL" "Latvian Lats"
   "LYD" "Libyan Dinar"
   "MAD" "Moroccan Dirham"
   "MDL" "Moldovan Leu"
   "MGF" "Malagasy Franc"
   "MKD" "Denar"
   "MMK" "Kyat"
   "MNT" "Tugrik"
   "MOP" "Pataca"
   "MRO" "Ouguiya"
   "MTL" "Maltese Lira"
   "MUR" "Mauritius Rupee"
   "MVR" "Rufiyaa"
   "MWK" "Kwacha"
   "MXN" "Mexican Nuevo Peso"
   "MYR" "Malaysian Ringgit"
   "MZM" "Metical"
   "NAD" "Namibia Dollar"
   "NGN" "Naira"
   "NIO" "Cordoba Oro"
   "NLG" "Netherlands Guilder"
   "NOK" "Norwegian Krone"
   "NPR" "Nepalese Rupee"
   "NZD" "New Zealand Dollar"
   "OMR" "Rial Omani"
   "PAB" "Balboa"
   "PEN" "Nuevo Sol"
   "PGK" "Kina"
   "PHP" "Philippine Peso"
   "PKR" "Pakistan Rupee"
   "PLN" "Zloty"
   "PLZ" "Zloty"
   "PTE" "Portuguese Escudo"
   "PYG" "Guarani"
   "QAR" "Qatari Rial"
   "ROL" "Leu"
   "RUR" "Russian Ruble"
   "RWF" "Rwanda Franc"
   "SAR" "Saudi Riyal"
   "SBD" "Solomon Islands Dollar"
   "SCR" "Seychelles Rupee"
   "SDD" "Sudanese Dinar"
   "SEK" "Swedish Krona"
   "SGD" "Singapore Dollar"
   "SHP" "St. Helena Pound"
   "SIT" "Tolar"
   "SKK" "Slovak Koruna"
   "SLL" "Leone"
   "SOS" "Somali Shilling"
   "SRG" "Surinam Guilder"
   "STD" "São Tomé and Príncipe Dobra"
   "SVC" "El Salvador Colon"
   "SYP" "Syrian Pound"
   "SZL" "Lilangeni"
   "THB" "Baht"
   "TJR" "Tajik Ruble"
   "TMM" "Manat"
   "TND" "Tunisian Dollar"
   "TOP" "Pa'anga"
   "TPE" "Timor Escudo"
   "TRY" "Turkish Lira"
   "TTD" "Tinidad and Tobago Dollar"
   "TWD" "New Taiwan Dollar"
   "TZS" "Tanzanian Shilling"
   "UAG" "Hryvna"
   "UAK" "Karbovanets"
   "UGX" "Uganda Shilling"
   "USD" "US Dollar"
   "UYU" "Peso Uruguayo"
   "UZS" "Uzbekistan Sum"
   "VEB" "Bolivar"
   "VND" "Dong"
   "VUV" "Vatu"
   "WST" "Tala"
   "XAF" "CFA Franc BEAC"
   "XCD" "East Caribbean Dollar"
   "XEU" "Euro"
   "XOF" "CFA Franc BCEAO"
   "XPF" "CFP Franc"
   "YER" "Yemeni Rial"
   "YUM" "New Dinar"
   "ZAL" "Financial Rand"
   "ZAR" "Rand"
   "ZMK" "Kwacha"
   "ZRN" "New Zaire"
   "ZWD" "Zimbabwe Dollar"})